### PR TITLE
vault-env: add version to secret cache key

### LINKED ISSUE #794: vault-env: the secret cache only caches 1 version of the secret
**Describe the bug**:
If one "wanted" to use different versions of the same secret in different env variables, the values would all end up beeing the ones of the first cached version, as the cache key access is based on path and not path+version.

**Expected behaviour**:
make the cache key out of path+version

**Steps to reproduce the bug**:
set 2 env variables:
* one with vault:/foo#bar#1
* one with vault:/foo#bar#2

Othe the env variables with end up with the value of the first fetched version.

### PR DESCRIPTION
**Pull request by bonifaido**
Signed-off-by: Nandor Kracser <bonifaido@gmail.com>

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #794 
| License         | Apache 2.0

### What's in this PR?

The version was missing from the secret cache key.

### CODE REVIEW

File: cmd/vault-env/main.go [hunk 1]
```diff
@@ -216,16 +216,18 @@ func main() {
...
+		if secret = secretCache[secretCacheKey]; secret == nil {
 			if update {
 				secret, err = client.RawClient().Logical().Write(valuePath, map[string]interface{}{})
 				if err != nil {
 					logger.Fatalln("failed to write secret to path:", valuePath, err.Error())
 				}
-				secretCache[valuePath] = secret
+				secretCache[secretCacheKey] = secret
 			} else {
 				secret, err = client.RawClient().Logical().ReadWithData(valuePath, map[string][]string{"version": {version}})
```
Comment (primeroz) [inline cmd/vault-env/main.go]: Does this mean we can only read from kv2 ?

Comment (bonifaido) [reply cmd/vault-env/main.go]: No, this is just the cache key in the map.
