### PR TITLE
cli: handle signals properly

### LINKED ISSUE #1128: Configurer does not respect signals
**Describe the bug**:
When trying to stop configurer gracefully (eg. `docker stop`) it exits with code 2.

**Expected behaviour**:
Configurer should exit with 0.

**Steps to reproduce the bug**:
1. Start configurer in a container
1. Stop it with `docker stop`

**Additional context**:
This causes  problem around restart policies: on-failure is triggered even when we attempt to stop the container gracefully.

### PR DESCRIPTION
**Pull request by bonifaido**
Signed-off-by: Nandor Kracser <bonifaido@gmail.com>

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | yes
| Deprecations?   | no
| Related tickets | fixes #1128 
| License         | Apache 2.0

### What's in this PR?

Handling signals, and do a 0 status code exit.

### Why?

If signals are not captured the CLI exits with status code 2.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### CODE REVIEW

File: cmd/bank-vaults/main.go [hunk 1]
```diff
@@ -99,6 +101,16 @@ var rootCmd = &cobra.Command{
 // Execute adds all child commands to the root command sets flags appropriately.
 // This is called by main.main(). It only needs to happen once to the rootCmd.
 func execute() {
+	// Handle signals to prevent bad exit codes on `docker stop`.
+	// TODO: robably a more sophisticated exit procedure should be implemented in the future.
```
Comment (sagikazarmark) [inline cmd/bank-vaults/main.go:105]:
```suggestion
	// TODO: probably a more sophisticated exit procedure should be implemented in the future.
```

Comment (sagikazarmark) [reply cmd/bank-vaults/main.go:105]: Yeah, that's not a bad idea. :D

File: cmd/bank-vaults/main.go [hunk 2]
```diff
@@ -99,6 +101,16 @@ var rootCmd = &cobra.Command{
...
+	sigs := make(chan os.Signal, 1)
+	signal.Notify(sigs, syscall.SIGTERM, syscall.SIGINT, syscall.SIGABRT)
+	go func() {
+		for range sigs {
```
Comment (sagikazarmark) [inline cmd/bank-vaults/main.go:109]: No need for `for`. `<-sigs` should work.

**Review by pbalogh-sa — APPROVED** [review]

**Review by sagikazarmark — APPROVED** [review]
