### PR TITLE
Webhook ecr

### LINKED ISSUE #791: [Feature-Request] Mutation webhook cannot get image command from ECR
**Describe the bug**:
The mutation webhook cannot find the `command` of a docker image in [ECR](https://aws.amazon.com/ecr/) if the pod spec does not contain `imagePullSecrets` set. i.e. when kubernetes uses the instance metadata and AWS Roles to access the registry.

**Expected behaviour**:
The mutation webhook should be able to access the registry the same way docker would be able to, maybe by using something like [credential helpers](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers), to be able to integrate with [existing tools](https://github.com/awslabs/amazon-ecr-credential-helper)

**Steps to reproduce the bug**:
- Run a Kubernetes cluster on AWS
- Have the kubernetes nodes have a role with [permissions](https://kubernetes.io/docs/concepts/containers/images/#using-amazon-elastic-container-registry) to pull images from the ECR registry
- deploy bank-vaults to the cluster (or just the webhook if you have a vault server running somewhere already)
- create a deployment of some image in the ECR registry that uses vault (example yaml below).

**Additional context**:

**Environment details**:
- Kubernetes version v1.11.10:
- Cloud-provider/provisioner: AWS
- vault-secrets-webhook version: `0.6.3` (chart version `0.6.5`)
- Install method: helm chart
- Logs from the misbehaving component (and any other relevant logs):
```
vault-secrets-webhook time="2019-12-09T19:27:03Z" level=debug msg="reviewing request e14e549f-1ab9-11ea-a569-0ed3761560b6, named: sample-app/" app=vault-secrets-webhook
vault-secrets-webhook time="2019-12-09T19:27:03Z" level=debug msg="Successfully connected to the API" app=vault-secrets-webhook
vault-secrets-webhook time="2019-12-09T19:27:03Z" level=debug msg="No pod init containers were mutated" app=vault-secrets-webhook
vault-secrets-webhook time="2019-12-09T19:27:03Z" level=info msg="found no credentials for registry , assuming it is public"
vault-secrets-webhook time="2019-12-09T19:27:03Z" level=info msg="I'm using registry https://<AWS_ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com"
vault-secrets-webhook 2019/12/09 19:27:03 registry.manifest.get url=https://<AWS_ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/v2/sample-app/manifests/latest repository=sample-app reference=latest
vault-secrets-webhook time="2019-12-09T19:27:03Z" level=error msg="admission webhook error: cannot download manifest for image: Get https://<AWS_ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/v2/sample-app/manifests/latest: http: non-successful response (status=401 body=\"Not Authorized\\n\")" app=vault-secrets-webhook
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```yaml
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: sample-app
    name: sample-app
    namespace: sample-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: sample-app
    template:
      metadata:
        annotations:
          vault.security.banzaicloud.io/vault-role: sample-app
        labels:
          app: sample-app
        name: sample-app
        namespace: sample-app
      spec:
        containers:
        - env:
          - name: SECRET_VALUE
             value: vault:secrets/data/some/super/secret#key
          image: <AWS_ACCOUNT>.dkr.ecr.us-east-1.amazonaws.com/sample-app:latest
          imagePullPolicy: IfNotPresent
          name: sample-app
```

**Possible solutions**:
Instead of using the registry api [directly](https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-secrets-webhook/registry/registry.go#L134) passing in an user+password. Do something along the line of the docker cli and support credential helpers

Or maybe a more direct approach taking into account AWS directly, the way that #479 did.

/kind bug

### PR DESCRIPTION
**Pull request by Kasama**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | [yes](https://github.com/banzaicloud/bank-vaults/pull/792/files#diff-e65209c34717a2345f9c0f910b76a646R112) - function signature change
| Deprecations?   | no
| Related tickets | fixes #791 
| License         | Apache 2.0

### Checklist

- [ ] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [ ] Logging code meets the guideline (TODO)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

- [ ] Add tests
- [x] Use go-cache to cache image as well as the credentials

### CODE REVIEW

File: cmd/vault-secrets-webhook/registry/registry.go [hunk 1]
```diff
@@ -340,29 +348,58 @@ func (k *ContainerInfo) Collect(container *corev1.Container, podSpec *corev1.Pod
...
+				req := ecr.GetAuthorizationTokenInput{
+					RegistryIds: []*string{aws.String(ecrRegistryID)},
+				}
 
-			resp, err := svc.GetAuthorizationToken(&req)
-			if err != nil {
-				return err
+				resp, err := svc.GetAuthorizationToken(&req)
+				if err != nil {
+					return err
```
Comment (Kasama) [inline cmd/vault-secrets-webhook/registry/registry.go]: I think it's best to assume the repository is public instead of returning an error when there is no role or other credential provider for AWS. This way it will be consistent with the other branches and try to get the image information even without credentials

Comment (bonifaido) [reply cmd/vault-secrets-webhook/registry/registry.go]: Yeah I agree, my only intention was here that ECR doesn't have the option to host images publicly, at least currently.

**Comment by bonifaido** [comment]
One of the tests fail here because it would like to connect to AWS, I think we should remove that part now.

**Comment by Kasama** [comment]
I'm not very familiar with go, so I'm not sure how I could test this new AWS flow mocking the actual AWS request. From what I've googled, it would require writing a wrapper interface and implement that in a mock. Is this the correct way to go about that?

**Comment by bonifaido** [comment]
I will manually test this as I usually do, but we can add a real ECR test to the integration test here. That should be a part of another PR.

**Comment by Kasama** [comment]
Thanks! Glad to help, if there's anything else I can do, please ping me!
